### ISSUE TITLE
Error on 128 GB file

### ISSUE THREAD

**Issue by ImJoke** [zakcutner/fastgrep#2]
Error when trying to find text from a file that is 128 gb or larger
<img width="1241" alt="image" src="https://github.com/zakcutner/fastgrep/assets/55929550/3a95666f-e002-4136-a3cd-d5ded66b5040">

**Comment by zakcutner** [comment]
Hello! I think this is because your file contains some characters that are not valid UTF-8. I haven't done any work on this project for a bit, but it currently only supports UTF-8 characters unfortunately.

**Comment by ImJoke** [comment]
> Hello! I think this is because your file contains some characters that are not valid UTF-8. I haven't done any work on this project for a bit, but it currently only supports UTF-8 characters unfortunately.

Owh okay thanks, but it's work fine in ripgrep
